import { upsertAgent } from '../services/agentService';

const AGENTS = [
  {
    name: 'AutoGPT',
    slug: 'autogpt',
    resource_type: 'agent',
    type: 'agent',
    description: 'An autonomous AI agent that chains together thoughts and executes tasks. Self-directed, self-correcting.',
    author_github: 'Significant-Gravitas',
    repository_url: 'https://github.com/Significant-Gravitas/AutoGPT',
    homepage_url: 'https://news.agpt.co',
    license: 'MIT',
    tier1_category: 'agents',
    tier1_subcategory: 'autonomous',
    tier2_categories: ['autonomous', 'multi-step'],
    use_cases: ['automation', 'research', 'creative'],
    complexity_level: 'advanced',
    deployment_type: 'self-hosted',
    required_skills: ['openai', 'pinecone', 'tools'],
    tags: ['autonomous', 'gpt4', 'agent', 'python'],
    tools_used: ['openai', 'google', 'file-system', 'web-browser'],
    verification_score: 0.97,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 162000,
    forks: 44000,
    watchers: 3200,
  },
  {
    name: 'CrewAI',
    slug: 'crewai',
    resource_type: 'agent',
    type: 'agent',
    description: 'Framework for orchestrating role-playing, autonomous AI agents. Create teams of agents that work together.',
    author_github: 'joaomdmoura',
    repository_url: 'https://github.com/joaomdmoura/crewAI',
    homepage_url: 'https://www.crewai.com',
    license: 'MIT',
    tier1_category: 'agents',
    tier1_subcategory: 'multi-agent',
    tier2_categories: ['orchestration', 'multi-agent'],
    use_cases: ['automation', 'enterprise', 'research'],
    complexity_level: 'intermediate',
    deployment_type: 'self-hosted',
    required_skills: ['crewai', 'openai', 'langchain'],
    tags: ['multi-agent', 'crew', 'orchestration', 'python'],
    tools_used: ['openai', 'crewai', 'langchain'],
    verification_score: 0.94,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 22500,
    forks: 3200,
    watchers: 480,
  },
  {
    name: 'LangGraph Multi-Agent State Machine',
    slug: 'langgraph-multi-agent',
    resource_type: 'workflow',
    type: 'workflow',
    description: 'Build stateful, multi-actor applications with LLMs. Cycle and branching support for complex agent flows.',
    author_github: 'langchain-ai',
    repository_url: 'https://github.com/langchain-ai/langgraph',
    homepage_url: 'https://langchain-ai.github.io/langgraph',
    license: 'MIT',
    tier1_category: 'workflows',
    tier1_subcategory: 'state-machine',
    tier2_categories: ['state-machine', 'multi-agent'],
    use_cases: ['automation', 'code', 'enterprise'],
    complexity_level: 'advanced',
    deployment_type: 'self-hosted',
    required_skills: ['langgraph', 'langchain', 'state'],
    tags: ['langgraph', 'multi-agent', 'state', 'python'],
    tools_used: ['langgraph', 'openai', 'tavily'],
    verification_score: 0.91,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 9200,
    forks: 1100,
    watchers: 90,
  },
  {
    name: 'OpenInterpreter Code Agent',
    slug: 'open-interpreter',
    resource_type: 'agent',
    type: 'agent',
    description: 'Let language models run code locally. Execute shell commands, manipulate files, browse the web.',
    author_github: 'OpenInterpreter',
    repository_url: 'https://github.com/OpenInterpreter/open-interpreter',
    homepage_url: 'https://openinterpreter.com',
    license: 'MIT',
    tier1_category: 'agents',
    tier1_subcategory: 'code-execution',
    tier2_categories: ['code-execution', 'terminal'],
    use_cases: ['automation', 'code', 'data'],
    complexity_level: 'beginner',
    deployment_type: 'self-hosted',
    required_skills: ['openai', 'shell', 'file-system'],
    tags: ['interpreter', 'code-exec', 'terminal', 'python'],
    tools_used: ['openai', 'python', 'shell'],
    verification_score: 0.85,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: false, active_contributors: true, recent_commits: true },
    stars: 52000,
    forks: 6800,
    watchers: 800,
  },
  {
    name: 'Semantic Kernel SDK',
    slug: 'microsoft-semantic-kernel',
    resource_type: 'tool',
    type: 'tool',
    description: 'Microsoft SDK that integrates LLMs with conventional programming languages. Plugin architecture for AI.',
    author_github: 'microsoft',
    repository_url: 'https://github.com/microsoft/semantic-kernel',
    homepage_url: 'https://learn.microsoft.com/semantic-kernel',
    license: 'MIT',
    tier1_category: 'tools',
    tier1_subcategory: 'sdk',
    tier2_categories: ['sdk', 'integration'],
    use_cases: ['enterprise', 'automation', 'code'],
    complexity_level: 'intermediate',
    deployment_type: 'api',
    required_skills: ['semantic-kernel', 'dotnet', 'openai'],
    tags: ['microsoft', 'sdk', 'kernel', 'dotnet'],
    tools_used: ['openai', 'azure', 'dotnet'],
    verification_score: 0.96,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 19800,
    forks: 4100,
    watchers: 320,
  },
  {
    name: 'ChromaDB Memory',
    slug: 'chromadb-memory',
    resource_type: 'memory',
    type: 'memory',
    description: 'Embedding database for AI memory. Store and retrieve vector embeddings for agent context.',
    author_github: 'chroma-core',
    repository_url: 'https://github.com/chroma-core/chroma',
    homepage_url: 'https://www.trychroma.com',
    license: 'Apache-2.0',
    tier1_category: 'memory',
    tier1_subcategory: 'vector',
    tier2_categories: ['vector', 'search'],
    use_cases: ['research', 'code', 'enterprise'],
    complexity_level: 'beginner',
    deployment_type: 'self-hosted',
    required_skills: ['chroma', 'embeddings'],
    tags: ['vector-db', 'embeddings', 'memory', 'python'],
    tools_used: ['openai', 'numpy', 'sqlite'],
    verification_score: 0.88,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 14100,
    forks: 1700,
    watchers: 160,
  },
  {
    name: 'LlamaIndex Query Router',
    slug: 'llamaindex-agent-router',
    resource_type: 'router',
    type: 'router',
    description: 'Intelligent query routing across multiple data sources. Auto-generates queries based on user intent.',
    author_github: 'run-llama',
    repository_url: 'https://github.com/run-llama/llama_index',
    homepage_url: 'https://www.llamaindex.ai',
    license: 'MIT',
    tier1_category: 'routers',
    tier1_subcategory: 'query',
    tier2_categories: ['query', 'routing'],
    use_cases: ['research', 'data', 'enterprise'],
    complexity_level: 'intermediate',
    deployment_type: 'api',
    required_skills: ['llamaindex', 'embeddings', 'queries'],
    tags: ['llamaindex', 'routing', 'queries', 'rag'],
    tools_used: ['openai', 'pinecone', 'notion'],
    verification_score: 0.93,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 31500,
    forks: 5200,
    watchers: 480,
  },
  {
    name: 'Qdrant Vector Store',
    slug: 'qdrant-vector-store',
    resource_type: 'memory',
    type: 'memory',
    description: 'High-performance vector similarity search engine. Perfect for AI agent long-term memory.',
    author_github: 'qdrant',
    repository_url: 'https://github.com/qdrant/qdrant',
    homepage_url: 'https://qdrant.tech',
    license: 'Apache-2.0',
    tier1_category: 'memory',
    tier1_subcategory: 'vector',
    tier2_categories: ['vector', 'search'],
    use_cases: ['research', 'enterprise', 'code'],
    complexity_level: 'intermediate',
    deployment_type: 'api',
    required_skills: ['qdrant', 'embeddings', 'rust'],
    tags: ['vector-db', 'search', 'rust'],
    tools_used: ['openai', 'qdrant', 'python'],
    verification_score: 0.93,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 20100,
    forks: 2200,
    watchers: 160,
  },
  {
    name: 'HuggingFace Transformers Skill',
    slug: 'huggingface-transformers-skill',
    resource_type: 'skill',
    type: 'skill',
    description: 'Integrate Hugging Face models into Hermes agents. Text generation, embeddings, classification.',
    author_github: 'huggingface',
    repository_url: 'https://github.com/huggingface/transformers',
    homepage_url: 'https://huggingface.co/transformers',
    license: 'Apache-2.0',
    tier1_category: 'skills',
    tier1_subcategory: 'nlp',
    tier2_categories: ['nlp', 'ml'],
    use_cases: ['ml', 'research', 'code'],
    complexity_level: 'intermediate',
    deployment_type: 'self-hosted',
    required_skills: ['transformers', 'pytorch'],
    tags: ['huggingface', 'transformers', 'models', 'ml'],
    tools_used: ['pytorch', 'transformers', 'datasets'],
    verification_score: 0.99,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 130000,
    forks: 27000,
    watchers: 2200,
  },
  {
    name: 'Pydantic AI Agent Framework',
    slug: 'pydantic-ai',
    resource_type: 'agent',
    type: 'agent',
    description: 'Type-safe Python AI agent framework with structured output and validated responses.',
    author_github: 'pydantic',
    repository_url: 'https://github.com/pydantic/pydantic-ai',
    homepage_url: 'https://ai.pydantic.dev',
    license: 'MIT',
    tier1_category: 'agents',
    tier1_subcategory: 'structured',
    tier2_categories: ['structured', 'validation'],
    use_cases: ['code', 'automation', 'enterprise'],
    complexity_level: 'intermediate',
    deployment_type: 'self-hosted',
    required_skills: ['pydantic', 'python', 'openai'],
    tags: ['pydantic', 'validation', 'types', 'python'],
    tools_used: ['openai', 'pydantic', 'httpx'],
    verification_score: 0.90,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 8400,
    forks: 720,
    watchers: 85,
  },
  {
    name: 'Haystack RAG Pipeline',
    slug: 'haystack-document-pipeline',
    resource_type: 'workflow',
    type: 'workflow',
    description: 'NLP pipelines for semantic search and LLM workflows. Build retrieval-augmented generation.',
    author_github: 'deepset-ai',
    repository_url: 'https://github.com/deepset-ai/haystack',
    homepage_url: 'https://haystack.deepset.ai',
    license: 'Apache-2.0',
    tier1_category: 'workflows',
    tier1_subcategory: 'rag',
    tier2_categories: ['rag', 'search'],
    use_cases: ['research', 'automation', 'enterprise'],
    complexity_level: 'intermediate',
    deployment_type: 'self-hosted',
    required_skills: ['haystack', 'embeddings', 'retrieval'],
    tags: ['haystack', 'rag', 'search', 'python'],
    tools_used: ['elasticsearch', 'openai', 'transformers'],
    verification_score: 0.90,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 15200,
    forks: 2800,
    watchers: 200,
  },
  {
    name: 'LangChain Agent Builder',
    slug: 'langchain-agent-builder',
    resource_type: 'agent',
    type: 'agent',
    description: 'Build and deploy AI agents with LangChain. Supports multi-step reasoning and tool use.',
    author_github: 'langchain-ai',
    repository_url: 'https://github.com/langchain-ai/langchain',
    homepage_url: 'https://python.langchain.com',
    license: 'MIT',
    tier1_category: 'agents',
    tier1_subcategory: 'chain',
    tier2_categories: ['chain', 'tool-using'],
    use_cases: ['automation', 'research'],
    complexity_level: 'intermediate',
    deployment_type: 'self-hosted',
    required_skills: ['langchain', 'openai', 'tools'],
    tags: ['langchain', 'agents', 'llm', 'python'],
    tools_used: ['openai', 'tavily', 'python'],
    verification_score: 0.92,
    verification_status: 'verified',
    verification_checks: { has_readme: true, has_tests: true, active_contributors: true, recent_commits: true },
    stars: 92000,
    forks: 14000,
    watchers: 1800,
  },
];

export async function seedDatabase(): Promise<number> {
  console.log('Seeding Hermes Eco database...');

  let inserted = 0;

  for (const agent of AGENTS) {
    try {
      await upsertAgent(agent);
      console.log(`  ${agent.name} (${agent.resource_type}) upserted`);
      inserted++;
    } catch (err: any) {
      console.log(`  Skipped: ${agent.name} - ${err.message?.slice(0, 80)}`);
    }
  }

  console.log(`\n  Total: ${inserted} agents processed`);
  return inserted;
}
